# vim: set ft=yaml ts=2 expandtab:
---

- name: assertions
  assert:
    that:
      - chrony_status in chrony_stati

- name: include_tasks
  include_tasks:
      file: "{{ chrony_status }}.yml"

...
